### PR TITLE
Ruby 2.4 deprecates Fixnum, match Integer first.

### PR DESCRIPTION
**Pull request by lilydjwg**
This avoids the warning.

### CODE REVIEW

**Comment by sjbach** [comment]
Thanks for the patch.  Looks like it includes some unintended changes - can you verify?

**Comment by lilydjwg** [comment]
I've run `make`, and those generated files changed a lot. Should I remove them (and maybe run `make` in another commit)?

**Comment by sjbach** [comment]
If I run `make clean` and `make` again in your branch, the unwanted part of the diff goes away.  (I.e. the only part of the diff in `autoload/lustyjuggler.vim` that is retained is the `when Integer` check.)  How about for you?

**Comment by sjbach** [comment]
Great.  Merged, thanks for the fix. :-)

**Pull request merged**
